# Generated by Django 5.2.8 on 2025-12-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
