# Generated by Django 5.2.8 on 2025-12-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmetics', '0002_service_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Wig Installation', 'Wig Installation'), ('Braided Hairstyles', 'Braided Hairstyles'), ('Facial Services', 'Facial Services'), ('Nail Art Design Services', 'Nail Art Design Services'), ('Massage Services', 'Massage Services')], default=('C:\\Users\\Administrator\\AppData\\Local\\Python\\pythoncore-3.14-64\\python314.zip',), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
